/:
  controller: Base
  action: index

/signup:
  controller: Auth
  action: signupForm

/register:
  controller: Auth
  action: signup

/login:
  controller: Auth
  action: loginForm

/login-post:
  controller: Auth
  action: login

/logout:
  controller: Auth
  action: logout

/dashboard:
  controller: PageController
  action: index

/activation:
  controller: Auth
  action: activation

/forgot:
  controller: Auth
  action: forgotForm

/forgot-post:
  controller: Auth
  action: forgot

/reset-password:
  controller: Auth
  action: resetForm

/reset-password-post:
  controller: Auth
  action: reset

/pages:
  controller: "PageController"
  action: "index"

/create:
  controller: "PageController"
  action: "createForm"

/create_post:
  controller: "PageController"
  action: "create"

/edit:
  controller: "PageController"
  action: "editForm"

/update:
  controller: "PageController"
  action: "update"

/delete:
  controller: "PageController"
  action: "delete"

/users:
  controller: AdminUserController
  action: "index"

/users/update-role:
  controller: AdminUserController
  action: "updateRole"

/users/create:
  controller: AdminUserController
  action: createForm

/users/create-post:
  controller: AdminUserController
  action: create

/users/delete:
  controller: AdminUserController
  action: delete
